### ISSUE TITLE
utilities.js broken

### ISSUE THREAD

**Issue by wettowelreactor** [graffiome/GitSecure#9]
utilities.js has two async function calls that update a value. The way it is currently implemented the value will return immediately before the async calls complete presenting the wrong data.

**Comment by rmagee88** [comment]
I believe I've refactored that completely out... so shouldn't be an issue
moving forward

-Rich

**Comment by wettowelreactor** [comment]
Koz is using it in his code. If you have an alternative he should be using please let him know. 

--Camille Roussel
